apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels: 
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: nexus:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - name: nexus-configs
          mountPath: /home/nexus
      volumes:
      - name: nexus-configs
        configMap:
          name: nexus-config
