apiVersion: v1
kind: Pod
metadata:
  name: nexus
  labels: 
    app: nexus
spec:
  containers:
  - name: nexus
    image: sonatype/nexus:latest
    ports:
    - containerPort: 8081
    readinessProbe:
      httpGet:
        path: /nexus
        port: 8081
    volumeMounts:
    - name: nexus-configs
      mountPath: /opt/sonatype/nexus/etc/nexus-default.properties
  volumes:
  - name: nexus-configs
    configMap:
      name: nexus-config

