apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:latest
    ports:
    - containerPort: 8080
    env:
    - name: JENKINS_OPTS
      value: "--prefix=/jenkins"
    readinessProbe:
      httpGet:
       path: /jenkins/whoAmI/
       port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports: 
  - protocol: TCP
    port: 8080
  type: NodePort
