apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
data:
  server.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <Server port="8005" shutdown="SHUTDOWN">
        <Listener className="org.apache.catalina.startup.VersionLoggerListener"/>
        <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on"/> <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"/>
        <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
        <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"/>
        <Service name="Catalina">
            <Connector port="8080" relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"
                       maxThreads="150" minSpareThreads="25" connectionTimeout="20000" enableLookups="false"
                       maxHttpHeaderSize="8192" protocol="HTTP/1.1" useBodyEncodingForURI="true" redirectPort="8443"
                       acceptCount="100" disableUploadTimeout="true" bindOnInit="false"/>
            <Engine name="Catalina" defaultHost="localhost">
                <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">
                    <Context path="/jira" docBase="${catalina.home}/atlassian-jira" reloadable="false" useHttpOnly="true">
                        <Resource name="UserTransaction" auth="Container" type="javax.transaction.UserTransaction"
                                  factory="org.objectweb.jotm.UserTransactionFactory" jotm.timeout="60"/>
                        <Manager pathname=""/>
                        <JarScanner scanManifest="false"/>
                        <Valve className="org.apache.catalina.valves.StuckThreadDetectionValve" threshold="120" />
                    </Context>
                </Host>
                <Valve className="org.apache.catalina.valves.AccessLogValve"
                       pattern="%a %{jira.request.id}r %{jira.request.username}r %t &quot;%m %U%q %H&quot; %s %b %D &quot;%{Referer}i&quot; &quot;%{User-Agent}i&quot; &quot;%{jira.request.assession.id}r&quot;"/>
            </Engine>
        </Service>
    </Server>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
  labels: 
    app: jira
spec:
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: bobcrutchley/jira:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /jira/status
            port: 8080
        volumeMounts:
        - name: jira-configs
          mountPath: /home/jira/conf
      volumes:
      - name: jira-configs
        configMap:
          name: jira-config
---
apiVersion: v1
kind: Service
metadata:
  name: jira
spec:
  selector:
    app: jira
  ports: 
  - protocol: TCP
    port: 8080
  type: NodePort

