apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream letsencrypt {
        server letsencrypt:80 max_fails=0 fail_timeout=1s;
    }
    server {
        listen 80;
        location / {
            return 200 "OK";
        }
        location ^~ /.well-known/acme-challenge/ {
            proxy_pass http://letsencrypt;
        }
        location /jenkins/ {
            proxy_pass http://jenkins:8080;
    		proxy_read_timeout  90;
    		proxy_set_header X-Forwarded-Host $host:$server_port;
    		proxy_set_header X-Forwarded-Server $host;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;
    		proxy_set_header X-Real-IP $remote_addr;
        }
        location /jira/ {
            proxy_pass http://jira:8080;
        }
        location /sonarqube/ {
            proxy_pass http://sonarqube:9000;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - name: nginx-configs
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-configs
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

