apiVersion: v1
kind: Pod
metadata:
  name: nexus
  labels: 
    app: nexus
spec:
   containers:
   - name: jenkins
     image: jenkins/jenkins:latest
     ports:
     - containerPort: 8080
     env:
     - name: JENKINS_OPTS
       value: "--prefix=/jenkins"

